version: "3.1"

services:
  auth_service:
    build:
      context: auth_service/
      dockerfile: Dockerfile
    restart: always
    container_name: "auth_service"
    hostname: "auth_service"
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - MONGO_DB_URI=mongodb://root:pass@auth_db:27017
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - network

  law_court:
    build:
      context: law_court/
      dockerfile: Dockerfile
    restart: always
    container_name: "law_court"
    hostname: "law_court"
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - MONGO_DB_URI=mongodb://root:pass@auth_db:27017
      - AUTH_SERVICE_URL=http://auth_service:8082
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - network
  




  auth_db:
    hostname: "auth_db"
    container_name: "auth_db"
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: authDB
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - auth_db:/data/db
    networks:
      - network

volumes:
  auth_db:
  mong_express_data:

networks:
  network:
    driver: bridge